#!/usr/bin/env bash
# Install NGINX web server
# Requirements:
#   Install nginx on your web-01
#   server
#   Nginx should be listening on port 80
#   When querying Nginx at its root / with a GET request (requesting a page)
#    using curl, it must return a page that contains the string Hello World!
#   As an answer file, write a Bash script that configures a new Ubuntu machine
#    to respect above requirements (this script will be run on the server itself)
#   You can’t use systemctl for restarting nginx


# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx

# add to firewall
sudo ufw 'Nginx HTTP'

# Append hello world to file
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo inginx -t

# start nginx server
sudo service nginx restart

sudo service nginx reload
